apiVersion: apps/v1
kind: Deployment
metadata:
  name: lochness-website
  labels:
    app: lochness-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lochness-website
  template:
    metadata:
      labels:
        app: lochness-website
    spec:
      containers:
      - name: lochness-website
        image: localhost/lochness-website:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lochness-website
spec:
  type: NodePort
  selector:
    app: lochness-website
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
